### ISSUE TITLE
It is messed up guys please clear folders & structure

### ISSUE THREAD

**Issue by BestNoob** [RaidMax/IW4M-Admin#119]
Hello guys,
i dk if you recognized it but its really messed up. As example runtimes exist 3x in the "STABLE" release
...\IW4MAdmin-2.2-stable\Lib\runtimes\runtimes
...\IW4MAdmin-2.2-stable\runtimes

And in the actual "nightly" the folder structure is different to Stable.

And the Setup/Installation etc. doesnt fit the latest builds.

Would be great when u fix this.

**Comment by RaidMax** [comment]
Stable is like 1.5 years old, nothing I’m going to do to address that. It doesn’t hurt anything so I’m not sure how it’s an issue. 

Pre release is setup properly. Please view the most up to date readme https://github.com/RaidMax/IW4M-Admin/blob/2.4-pr/README.md

It has the majority of config options, but the setup process is correct. Again I’m not sure exactly what the issue is.

**Comment by BestNoob** [comment]
Is there a difference between Verified Prereleases and not tagged with it ?
Because Version 2.3 Prerelease Feature 2 Build 133 
is the latest Verified

**Comment by RaidMax** [comment]
Any errors with stable is a user setup/installation error. I can promise you stable works as intended. 

Verified builds are only created when I merge a feature/bugfix branch. The last few builds are direct commits to the release branch. There's no end user difference.
