### ISSUE TITLE
StartIW4MAdmin.cmd

### ISSUE THREAD

**Issue by wkuzma** [RaidMax/IW4M-Admin#134]
seems StartIW4MAdmin.cmd is missing from the download

**Comment by RaidMax** [comment]
No it's not, you probably downloaded the source code instead of the actual release file:
![image](https://user-images.githubusercontent.com/6732771/82241940-965ec900-9902-11ea-8bb3-2cf274631ffa.png)

Please download releases from: https://github.com/RaidMax/IW4M-Admin/releases
Click on assets
Download the zip file that is _NOT_ marked `Source Code`

**Comment by wkuzma** [comment]
i just downloaded IW4MAdmin-2.2-stable and found it there

**Comment by RaidMax** [comment]
Correct. the source code is the uncompiled source. It would make no sense to include a start script for a program that isn’t even built. Only the binary releases include the start script.
