### ISSUE TITLE
DVAR "g_log" does not exist

### ISSUE THREAD

**Issue by 16BitShooter** [RaidMax/IW4M-Admin#173]
It's been a hot minute since I messed with this stuff. 
Anyway I couldn't get Pluto T6 to work with an older version of IW4M. So I decided to update and now it's like reverse. Pluto T6 works but IW5 won't and it gives this in the console;
![Capture](https://user-images.githubusercontent.com/31642248/94367302-4e7c5980-00cd-11eb-8e06-5a5867e87443.PNG)

Before I updated IW5 would work and T6 wouldn't. I tried googling around and didn't really find anything specific to my issue.

**Comment by RaidMax** [comment]
The “stable” version is 2 years old at this point. Both Pluto T6 and Pluto IW5 have been rewritten since then. Pre release supports both new versions of the respective game. Please view the readme faq for a solution to your issue https://github.com/RaidMax/IW4M-Admin/wiki/FAQ#could-not-get-the-dvar-value-for-version

The FAQ also has a step by step setup video linked as well.

**Comment by RaidMax** [comment]
Closing as no response, and this would be resolved by updated to the pre release.
