### ISSUE TITLE
[T6] Issues getting dvars after latest bootstrapper update.

### ISSUE THREAD

**Issue by TheFantasticLoki** [RaidMax/IW4M-Admin#251]
after updating to r3226 I can't connect to my server anymore using Version 2022.6.11.1 always with a failure to get a dvar value even tho I can see it outputting the value it says it could not grab in the server console window.
SharedLibraryCore.Exceptions.DvarException: Could not get the dvar value for g_log
   at IW4MAdmin.Application.ApplicationManager.InitializeServers()
   at IW4MAdmin.Application.ApplicationManager.Init()
   at IW4MAdmin.Application.Program.LaunchAsync(String[] args)
Fatal error during initialization
Could not get the dvar value for g_log

another run
[2022-06-12 01:33:42.522  FTL] Failed to initialize IW4MAdmin
SharedLibraryCore.Exceptions.DvarException: Could not get the dvar value for version
   at IW4MAdmin.Application.ApplicationManager.InitializeServers()
   at IW4MAdmin.Application.ApplicationManager.Init()
   at IW4MAdmin.Application.Program.LaunchAsync(String[] args)
Fatal error during initialization
Could not get the dvar value for version

**Comment by Ayymoss** [comment]
Known issue. The issue is with Pluto, not us. Please join Discord for updates. 

Pasting the message from pinned...

Guys. Pluto's RCon is currently bugged due to Pluto's latest release. Raid cannot resolve this issue as it's something that'll need to be amended by Pluto. 

You can downgrade your Pluto version to a previous, working version or remain on the latest and wait for a fix by Pluto's devs. 

_**This issue isn't resolvable by us.**_

Discord: https://discord.gg/ZZFK5p3

**Comment by RektInator** [comment]
Fixed in the latest release of Plutonium (r3259).
