### ISSUE TITLE
[Feature Request] Map Voting / Fast Restart on Single Map servers

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#31]
**Map Voting**
Can we get the possibility to allow people to map vote based on the percentage that's currently online? 
I think map voting should be disabled for servers with less than 4 people online. 

This would need to be a per-server setting so people can't vote in maps for single map only servers.

***
**Fast Restart on Single Map servers**
After the game finishes, the server should auto fast-restart instead of running the map again.
Please allow some time to pass before fast restarting for the kill cam and a look at the scoreboard.

This would also need to be per-server for servers with map rotation.

**Comment by RaidMax** [comment]
Both good requests, and both implemented in the past; see:

https://github.com/RaidMax/IW4M-Admin/tree/308427e6621729867eafde218079af10a74695ec/Plugins/VoteMap

and: https://github.com/RaidMax/IW4M-Admin/tree/308427e6621729867eafde218079af10a74695ec/Plugins/FastRestart

However, I deprecated them as they're more of a game independent feature and not generalizable.
Due to how MW2 game script is written, there is also a bug on highly popular servers that causes it to allocate too many strings and kicks everyone out after a few fast restarts without a map restart.

I think this type of feature is better implemented using GSC (gamescript). The fast restart which I have already done I can include in the source.

**Comment by MrAmos123** [comment]
Ahh, I see! I also did not know that, I think I will allow the server to restart the map, but I need to figure out how to reduce the Intermission Time, and honestly I don't know where to start with this, apparently it's in the game files, which seems a little bit too much effort for such a simple change, would you know how to modify the intermission time for 25-30 sec to 5-10 sec?

**Comment by RaidMax** [comment]
There's a DVAR `scr_intermission_time` that _should_ work, but I'm not sure how reliable it is.
I'm also closing this as it's not something I plan to add back for the code at this time.

**Comment by Bluscream** [comment]
Maybe these to things are worth plugins?
