### ISSUE TITLE
Server Message Color Change / New Color?

### ISSUE THREAD

**Issue by exeLocates** [RaidMax/IW4M-Admin#324]
Hello,

Is there anyway to change the color code of the "Server" from "Server: Message Here"
As it stands the regular color is green and the PM color is cyan, is there a config option to change the regular color??

If not, can this be implemented for further customization?

**In addition**, can the second Wildcard color be added to the "IngameAccentColorKey" option
Right now Wildcard points to "^:" for the in-game color.

Perhaps WildcardGreen could point to the second color which is "^;" for Dark Green?
Or darkRed = "^:" and darkGreen = "^;"?

If this is already added please let me know the color code, thank you!

**Comment by RaidMax** [comment]
So, it all depends on what the game engine supports.
Since you have not provided any game details I can't provide 100% accurate information.

IW4MAdmin by default does not apply any color codes to the server name prefix, so any color you're seeing before the message content is whatever the default game behavior is.

Some CoD games support the `sv_sayname` dvar which will accomplish what want. Ex: `set sv_sayname "^0Server:^7"`.
However, the color codes are engine/game specific and you would need to determine the correct color code you'd like.

Additionally, if the game supports tell/say raw you can use the `CustomSayName` in the iw4madmin settings to provide any color/format you would like as that overrides the default server name completely.

If you want to add additional color code mapping you can do that in the `<GameName>Parser.js`

Example: 
![image](https://github.com/RaidMax/IW4M-Admin/assets/6732771/5e53c003-1948-44de-93f1-b60a788494d2)

Obviously, they have to be color codes supported by the game, but it would allow you do renaming and usage such as (Color::Grey) in iw4madmin settings.
